# Generated by Django 4.2.30 on 2026-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinecycle',
            name='adaptive_status',
            field=models.CharField(choices=[('R_updated', 'R Updated'), ('R_skipped', 'R Skipped (no measurement)'), ('skipped', 'Skipped (error path)')], default='R_updated', help_text='Whether adaptive R was updated, skipped, or bypassed', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('slice_type__in', ['train', 'validation', 'test'])), name='chk_cycles_slice_type'),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('source_type__in', ['csv_replay', 'mysql_replay', 'live'])), name='chk_cycles_source_type'),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('preprocess_status__in', ['valid', 'interpolated', 'kept_last', 'skipped', 'invalid'])), name='chk_cycles_preprocess_status'),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('adaptive_status__in', ['R_updated', 'R_skipped', 'skipped'])), name='chk_cycles_adaptive_status'),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('cycle_status__in', ['ok', 'skipped_no_measurement', 'skipped_invalid', 'error'])), name='chk_cycles_cycle_status'),
        ),
    ]
