# Generated by Codex on 2026-05-08

from django.db import migrations, models


def normalize_dead_cycle_status(apps, schema_editor):
    PipelineCycle = apps.get_model("estimation", "PipelineCycle")
    PipelineCycle.objects.filter(cycle_status="skipped_invalid").update(
        cycle_status="skipped_no_measurement"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("estimation", "0007_live_dedupe_key_and_config_cleanup"),
    ]

    operations = [
        migrations.RunPython(normalize_dead_cycle_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="experimentrun",
            name="dataset_source",
            field=models.CharField(
                blank=True,
                help_text="Live source, device, or deployment description for this run",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="experimentconfig",
            name="Q",
            field=models.FloatField(
                default=0.05,
                help_text="Process noise runtime default",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinecycle",
            name="cycle_status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("skipped_no_measurement", "Skipped — No Measurement"),
                    ("error", "Error"),
                ],
                default="ok",
                max_length=30,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="pipelinecycle",
            name="chk_cycles_cycle_status",
        ),
        migrations.AddConstraint(
            model_name="pipelinecycle",
            constraint=models.CheckConstraint(
                check=models.Q(cycle_status__in=["ok", "skipped_no_measurement", "error"]),
                name="chk_cycles_cycle_status",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationsummary",
            name="variance_reduction",
            field=models.FloatField(
                blank=True,
                help_text="1 - var_diff_filtered / var_diff_raw; must be >= 0.20",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationsummary",
            name="rmse_ratio",
            field=models.FloatField(
                blank=True,
                help_text="rmse_filtered / rmse_arx; must be <= 1.05",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationsummary",
            name="mae_ratio",
            field=models.FloatField(
                blank=True,
                help_text="mae_filtered / mae_arx; must be <= 1.05",
                null=True,
            ),
        ),
    ]
