# Generated by Django 4.2.16 on 2026-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_set_pump_flow_default_to_001'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_hum_fan_off',
            field=models.FloatField(default=70.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_hum_fan_on',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_hum_mist_off',
            field=models.FloatField(default=65.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_hum_mist_on',
            field=models.FloatField(default=55.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_light_off_ldr',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_light_on_ldr',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_soil_pump_off',
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_soil_pump_on',
            field=models.FloatField(default=35.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_temp_fan_off',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='greenhousecontrolprofile',
            name='thresh_temp_fan_on',
            field=models.FloatField(default=32.0),
        ),
    ]
