from django.urls import path
from .views import (
    AlertListView,
    AlertMarkAllReadView,
    AlertMarkReadView,
    AMPCLatestRecommendationView,
    AMPCSchedulerStartView,
    AMPCSchedulerStopView,
    AMPCSchedulerView,
    AutoRecommendationView,
    AutoSettingsView,
    ChartView,
    ControlModeView,
    ControlProfileView,
    ControlStateView,
    DashboardOverviewView,
    DeviceCommandView,
    DeviceCommandHistoryView,
    DeviceStateListView,
    DeviceToggleView,
    ForecastView,
    IngestCommandAckView,
    IngestPendingCommandsView,
    IngestReadingsView,
    LatestReadingView,
    LoginView,
    SensorHistoryView,
    TelegramSettingsView,
    SetupView,
    SetupStatusView,
    ESP32ThresholdView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/setup/', SetupView.as_view(), name='auth-setup'),
    path('auth/setup-status/', SetupStatusView.as_view(), name='auth-setup-status'),
    path('dashboard/overview/', DashboardOverviewView.as_view(), name='dashboard-overview'),
    path('sensor-readings/latest/', LatestReadingView.as_view(), name='sensor-latest'),
    path('sensor-readings/chart/', ChartView.as_view(), name='sensor-chart'),
    path('sensor-readings/history/', SensorHistoryView.as_view(), name='sensor-history'),
    path('control/state/', ControlStateView.as_view(), name='control-state'),
    path('control/mode/', ControlModeView.as_view(), name='control-mode'),
    path('forecast/', ForecastView.as_view(), name='forecast'),
    path('auto-settings/', AutoSettingsView.as_view(), name='auto-settings'),
    path('control/auto-recommendation/', AutoRecommendationView.as_view(), name='auto-recommendation'),
    path('control/mpc-scheduler/', AMPCSchedulerView.as_view(), name='mpc-scheduler'),
    path('control/mpc-scheduler/start/', AMPCSchedulerStartView.as_view(), name='mpc-scheduler-start'),
    path('control/mpc-scheduler/stop/', AMPCSchedulerStopView.as_view(), name='mpc-scheduler-stop'),
    path('control/mpc/recommendations/latest/', AMPCLatestRecommendationView.as_view(), name='mpc-latest-recommendation'),
    path('control/profile/', ControlProfileView.as_view(), name='control-profile'),
    path('devices/', DeviceStateListView.as_view(), name='device-list'),
    path('devices/<str:device_code>/toggle/', DeviceToggleView.as_view(), name='device-toggle'),
    path('devices/<str:device_code>/command/', DeviceCommandView.as_view(), name='device-command'),
    path('device-commands/history/', DeviceCommandHistoryView.as_view(), name='device-command-history'),
    path('alerts/', AlertListView.as_view(), name='alert-list'),
    path('alerts/<int:pk>/mark_read/', AlertMarkReadView.as_view(), name='alert-mark-read'),
    path('alerts/mark_all_read/', AlertMarkAllReadView.as_view(), name='alert-mark-all-read'),
    path('ingest/readings/', IngestReadingsView.as_view(), name='ingest-readings'),
    path('ingest/commands/pending/', IngestPendingCommandsView.as_view(), name='ingest-pending-commands'),
    path('ingest/commands/<int:pk>/ack/', IngestCommandAckView.as_view(), name='ingest-command-ack'),
    path('settings/telegram/', TelegramSettingsView.as_view(), name='telegram-settings'),
    path('settings/thresholds/', ESP32ThresholdView.as_view(), name='esp32-thresholds'),
]
