"""
Initial migration — creates all five tables for the Adaptive Kalman pipeline.

Tables created:
  experiment_runs, experiment_configs, arx_artifacts,
  pipeline_cycles, evaluation_summaries

Generated by: handwritten (Django not available in build environment).
Verified against: estimation/models.py as of task #002 review fix.

Run with:
  cd Server/backend
  python manage.py migrate
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        # ── experiment_runs ───────────────────────────────────────────────
        migrations.CreateModel(
            name="ExperimentRun",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("offline_replay", "Offline Replay"),
                            ("live", "Live"),
                        ],
                        default="offline_replay",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "dataset_source",
                    models.CharField(
                        blank=True,
                        help_text="CSV path or MySQL table/query description used for this run",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "experiment_runs",
            },
        ),
        migrations.AddIndex(
            model_name="ExperimentRun",
            index=models.Index(fields=["status"], name="idx_runs_status"),
        ),
        migrations.AddIndex(
            model_name="ExperimentRun",
            index=models.Index(fields=["created_at"], name="idx_runs_created"),
        ),

        # ── experiment_configs ────────────────────────────────────────────
        migrations.CreateModel(
            name="ExperimentConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="estimation.experimentrun",
                    ),
                ),
                (
                    "x0",
                    models.FloatField(
                        default=0.0,
                        help_text="Initial state estimate; set to first observed Soil_Moisture before run starts",
                    ),
                ),
                ("P0", models.FloatField(default=1.0, help_text="Initial covariance")),
                (
                    "Q",
                    models.FloatField(
                        default=0.05,
                        help_text="Process noise; tuned on validation slice",
                    ),
                ),
                ("R0", models.FloatField(default=1.0, help_text="Initial measurement noise")),
                ("R_min", models.FloatField(default=0.05, help_text="Lower bound for adaptive R")),
                ("R_max", models.FloatField(default=25.0, help_text="Upper bound for adaptive R")),
                (
                    "alpha",
                    models.FloatField(
                        default=0.95,
                        help_text="EMA smoothing factor for adaptive R",
                    ),
                ),
                ("train_ratio", models.FloatField(default=0.6)),
                ("val_ratio", models.FloatField(default=0.2)),
                ("test_ratio", models.FloatField(default=0.2)),
                ("arx_na", models.IntegerField(default=2, help_text="Output lag order")),
                ("arx_nb", models.IntegerField(default=2, help_text="Input lag order")),
                ("arx_nk", models.IntegerField(default=1, help_text="Input delay")),
                (
                    "preprocessing_policy",
                    models.CharField(
                        choices=[
                            ("keep_last", "Keep Last Valid"),
                            ("interpolate", "Interpolate"),
                            ("skip", "Skip Update"),
                        ],
                        default="keep_last",
                        max_length=20,
                    ),
                ),
                ("raw_config_json", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "experiment_configs",
            },
        ),

        # ── arx_artifacts ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="ARXArtifact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arx_artifact",
                        to="estimation.experimentrun",
                    ),
                ),
                ("na", models.IntegerField()),
                ("nb", models.IntegerField()),
                ("nk", models.IntegerField()),
                ("n_train_samples", models.IntegerField()),
                ("train_start_ts", models.DateTimeField()),
                ("train_end_ts", models.DateTimeField()),
                (
                    "coefficients_json",
                    models.TextField(
                        help_text="JSON array of the full theta coefficient vector"
                    ),
                ),
                (
                    "input_cols_json",
                    models.TextField(
                        help_text="JSON array of input column names used (e.g. Temperature, Humidity, ...)"
                    ),
                ),
                ("output_col", models.CharField(default="Soil_Moisture", max_length=100)),
                ("rmse_train", models.FloatField(blank=True, null=True)),
                ("rmse_val", models.FloatField(blank=True, null=True)),
                ("mae_train", models.FloatField(blank=True, null=True)),
                ("mae_val", models.FloatField(blank=True, null=True)),
                ("artifact_path", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "arx_artifacts",
            },
        ),

        # ── pipeline_cycles ───────────────────────────────────────────────
        migrations.CreateModel(
            name="PipelineCycle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="estimation.experimentrun",
                    ),
                ),
                ("sample_ts", models.DateTimeField(help_text="Source timestamp from dataset")),
                (
                    "cycle_index",
                    models.IntegerField(
                        help_text="Sequential 0-based index within the run"
                    ),
                ),
                (
                    "slice_type",
                    models.CharField(
                        choices=[
                            ("train", "Train"),
                            ("validation", "Validation"),
                            ("test", "Test"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("csv_replay", "CSV Replay"),
                            ("mysql_replay", "MySQL Replay"),
                            ("live", "Live Sensor"),
                        ],
                        default="csv_replay",
                        max_length=20,
                    ),
                ),
                # Raw measurements
                ("raw_soil_moisture", models.FloatField(blank=True, null=True)),
                ("raw_temperature", models.FloatField(blank=True, null=True)),
                ("raw_humidity", models.FloatField(blank=True, null=True)),
                ("raw_light", models.FloatField(blank=True, null=True)),
                ("raw_drip", models.FloatField(blank=True, null=True)),
                ("raw_mist", models.FloatField(blank=True, null=True)),
                ("raw_fan", models.FloatField(blank=True, null=True)),
                # Preprocessing
                (
                    "preprocess_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("interpolated", "Interpolated"),
                            ("kept_last", "Kept Last Valid"),
                            ("skipped", "Skipped"),
                            ("invalid", "Invalid"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                # ARX prediction
                (
                    "arx_predicted",
                    models.FloatField(
                        blank=True,
                        help_text="ARX next-step prediction for Soil_Moisture; NULL if prediction was skipped",
                        null=True,
                    ),
                ),
                # Kalman internals
                (
                    "kf_x_prior",
                    models.FloatField(
                        blank=True, help_text="Prior estimate x^-_k", null=True
                    ),
                ),
                (
                    "kf_P_prior",
                    models.FloatField(
                        blank=True, help_text="Prior covariance P^-_k", null=True
                    ),
                ),
                (
                    "kf_innovation",
                    models.FloatField(
                        blank=True,
                        help_text="Innovation e_k = z_k - x^-_k",
                        null=True,
                    ),
                ),
                (
                    "kf_R",
                    models.FloatField(
                        blank=True, help_text="Adaptive R_k at this step", null=True
                    ),
                ),
                (
                    "kf_K",
                    models.FloatField(
                        blank=True, help_text="Kalman gain K_k", null=True
                    ),
                ),
                (
                    "kf_x_posterior",
                    models.FloatField(
                        blank=True, help_text="Filtered estimate x_k", null=True
                    ),
                ),
                (
                    "kf_P_posterior",
                    models.FloatField(
                        blank=True, help_text="Updated covariance P_k", null=True
                    ),
                ),
                # Cycle outcome
                (
                    "cycle_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("skipped_no_measurement", "Skipped — No Measurement"),
                            ("skipped_invalid", "Skipped — Invalid"),
                            ("error", "Error"),
                        ],
                        default="ok",
                        max_length=30,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pipeline_cycles",
                "ordering": ["run", "cycle_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="PipelineCycle",
            constraint=models.UniqueConstraint(
                fields=["run", "cycle_index"],
                name="uq_cycles_run_index",
            ),
        ),
        migrations.AddIndex(
            model_name="PipelineCycle",
            index=models.Index(fields=["run", "sample_ts"], name="idx_cycles_run_ts"),
        ),
        migrations.AddIndex(
            model_name="PipelineCycle",
            index=models.Index(fields=["run", "slice_type"], name="idx_cycles_run_slice"),
        ),

        # ── evaluation_summaries ──────────────────────────────────────────
        migrations.CreateModel(
            name="EvaluationSummary",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_summaries",
                        to="estimation.experimentrun",
                    ),
                ),
                (
                    "slice_type",
                    models.CharField(
                        choices=[
                            ("train", "Train"),
                            ("validation", "Validation"),
                            ("test", "Test"),
                        ],
                        max_length=15,
                    ),
                ),
                ("n_samples", models.IntegerField(default=0)),
                ("n_valid", models.IntegerField(default=0)),
                ("n_skipped", models.IntegerField(default=0)),
                ("n_error", models.IntegerField(default=0)),
                # ARX accuracy
                ("rmse_arx", models.FloatField(blank=True, null=True)),
                ("mae_arx", models.FloatField(blank=True, null=True)),
                # Kalman accuracy
                ("rmse_filtered", models.FloatField(blank=True, null=True)),
                ("mae_filtered", models.FloatField(blank=True, null=True)),
                # Good-enough metrics
                (
                    "var_diff_raw",
                    models.FloatField(
                        blank=True,
                        help_text="var(diff(raw_soil_moisture))",
                        null=True,
                    ),
                ),
                (
                    "var_diff_filtered",
                    models.FloatField(
                        blank=True,
                        help_text="var(diff(kf_x_posterior))",
                        null=True,
                    ),
                ),
                (
                    "variance_reduction",
                    models.FloatField(
                        blank=True,
                        help_text="1 - var_diff_filtered / var_diff_raw; must be >= 0.20 on test slice",
                        null=True,
                    ),
                ),
                (
                    "rmse_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="rmse_filtered / rmse_arx; must be <= 1.05 on test slice",
                        null=True,
                    ),
                ),
                (
                    "mae_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="mae_filtered / mae_arx; must be <= 1.05 on test slice",
                        null=True,
                    ),
                ),
                # Diagnostics
                ("innovation_mean", models.FloatField(blank=True, null=True)),
                ("innovation_std", models.FloatField(blank=True, null=True)),
                ("innovation_max_abs", models.FloatField(blank=True, null=True)),
                ("R_mean", models.FloatField(blank=True, null=True)),
                ("R_min_observed", models.FloatField(blank=True, null=True)),
                ("R_max_observed", models.FloatField(blank=True, null=True)),
                ("P_mean", models.FloatField(blank=True, null=True)),
                ("P_max", models.FloatField(blank=True, null=True)),
                # Pass/fail flags
                (
                    "pass_variance_reduction",
                    models.BooleanField(
                        blank=True,
                        help_text="True if variance_reduction >= 0.20",
                        null=True,
                    ),
                ),
                (
                    "pass_rmse_guardrail",
                    models.BooleanField(
                        blank=True,
                        help_text="True if rmse_ratio <= 1.05",
                        null=True,
                    ),
                ),
                (
                    "pass_mae_guardrail",
                    models.BooleanField(
                        blank=True,
                        help_text="True if mae_ratio <= 1.05",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "evaluation_summaries",
            },
        ),
        migrations.AlterUniqueTogether(
            name="EvaluationSummary",
            unique_together={("run", "slice_type")},
        ),
    ]
