# Generated by Django 4.2.30 on 2026-05-08 09:08

from datetime import timezone

from django.db import migrations, models
from django.db.models import Count, Max

_RAW_SENSOR_FIELDS = (
    "raw_soil_moisture",
    "raw_temperature",
    "raw_humidity",
    "raw_light",
    "raw_drip",
    "raw_mist",
    "raw_fan",
)


def _raw_sensor_tuple(cycle):
    return tuple(getattr(cycle, field) for field in _RAW_SENSOR_FIELDS)


def _live_ingest_key(run_id, sample_ts):
    ts = sample_ts
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    else:
        ts = ts.astimezone(timezone.utc)
    return f"live|{run_id}|{ts.isoformat()}"


def _delete_duplicate_live_timestamps(PipelineCycle):
    """Delete only safe duplicate live timestamps.

    Kalman posterior rows are stateful. If a duplicate timestamp sits before
    later cycles, deleting it would leave those later rows computed from a
    history that no longer exists. Therefore this only auto-deletes identical
    raw payload duplicates when the duplicate group reaches the run tail.
    """
    duplicate_groups = (
        PipelineCycle.objects.values("run_id", "sample_ts")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for group in duplicate_groups.iterator():
        rows = list(
            PipelineCycle.objects.filter(
                run_id=group["run_id"],
                sample_ts=group["sample_ts"],
            ).order_by("cycle_index", "id")
        )
        if len(rows) < 2:
            continue
        ids = [row.id for row in rows]
        max_idx_in_group = max(row.cycle_index for row in rows)
        run_max_idx = (
            PipelineCycle.objects.filter(run_id=group["run_id"])
            .aggregate(m=Max("cycle_index"))
            .get("m")
        )
        if run_max_idx is None:
            run_max_idx = max_idx_in_group

        ref_payload = _raw_sensor_tuple(rows[0])
        same_payload = all(_raw_sensor_tuple(row) == ref_payload for row in rows[1:])
        if not same_payload:
            raise ValueError(
                "estimation migration 0006: duplicate live (run_id, sample_ts) "
                "with conflicting raw sensor payloads. "
                f"run_id={group['run_id']}, sample_ts={group['sample_ts']!r}, "
                f"pipeline_cycles.id in {ids}. "
                "Resolve manually, then run migrate again."
            )

        if run_max_idx > max_idx_in_group:
            raise ValueError(
                "estimation migration 0006: duplicate live (run_id, sample_ts) "
                "has identical raw payloads, but later cycles exist whose Kalman "
                "state may depend on the duplicate row. "
                f"run_id={group['run_id']}, sample_ts={group['sample_ts']!r}, "
                f"max duplicate cycle_index={max_idx_in_group}, "
                f"run max cycle_index={run_max_idx}, pipeline_cycles.id in {ids}. "
                "Replay/recompute the run from a clean snapshot, or trim later "
                "cycles manually, then run migrate again."
            )

        delete_ids = [row.id for row in rows[1:]]
        if delete_ids:
            PipelineCycle.objects.filter(id__in=delete_ids).delete()


def _backfill_live_ingest_keys(PipelineCycle, batch_size=500):
    # Unique(run, ingest_dedupe_key) already exists from 0005. Move every row to
    # a per-id temporary key first so correcting stale live keys cannot collide
    # with another row that currently owns the desired final key.
    rows = []
    for cycle in PipelineCycle.objects.only("id", "ingest_dedupe_key").iterator():
        temp_key = f"tmp-live-cleanup|{cycle.id}"
        if cycle.ingest_dedupe_key != temp_key:
            cycle.ingest_dedupe_key = temp_key
            rows.append(cycle)
        if len(rows) >= batch_size:
            PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])
            rows = []
    if rows:
        PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])

    rows = []
    for cycle in PipelineCycle.objects.only(
        "id",
        "run_id",
        "sample_ts",
        "ingest_dedupe_key",
    ).iterator():
        key = _live_ingest_key(cycle.run_id, cycle.sample_ts)
        if cycle.ingest_dedupe_key != key:
            cycle.ingest_dedupe_key = key
            rows.append(cycle)
        if len(rows) >= batch_size:
            PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])
            rows = []
    if rows:
        PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])


def normalize_existing_rows(apps, schema_editor):
    """Convert pre-cleanup rows to the live-only vocabulary.

    Evaluation summaries are derived data; deleting them avoids unique collisions
    when old train/validation/test rows collapse into a single online segment.
    They can be recomputed with ``evaluate_online``.
    """
    ExperimentRun = apps.get_model("estimation", "ExperimentRun")
    PipelineCycle = apps.get_model("estimation", "PipelineCycle")
    EvaluationSummary = apps.get_model("estimation", "EvaluationSummary")
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if EvaluationSummary._meta.db_table not in existing_tables:
        schema_editor.create_model(EvaluationSummary)

    ExperimentRun.objects.exclude(run_type="live").update(run_type="live")
    PipelineCycle.objects.exclude(source_type="live").update(source_type="live")
    PipelineCycle.objects.exclude(slice_type="online").update(slice_type="online")
    _delete_duplicate_live_timestamps(PipelineCycle)
    _backfill_live_ingest_keys(PipelineCycle)
    EvaluationSummary.objects.all().delete()


def drop_pipeline_cycle_checks(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor,
            "pipeline_cycles",
        )
        for name in ("chk_cycles_slice_type", "chk_cycles_source_type"):
            if name in constraints:
                cursor.execute(f"ALTER TABLE pipeline_cycles DROP CONSTRAINT {name}")


def drop_arx_artifacts_table(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS arx_artifacts")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('estimation', '0005_pipelinecycle_ingest_dedupe_key'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_pipeline_cycle_checks, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='pipelinecycle',
                    name='chk_cycles_slice_type',
                ),
                migrations.RemoveConstraint(
                    model_name='pipelinecycle',
                    name='chk_cycles_source_type',
                ),
            ],
        ),
        migrations.RunPython(normalize_existing_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='experimentconfig',
            name='arx_na',
        ),
        migrations.RemoveField(
            model_name='experimentconfig',
            name='arx_nb',
        ),
        migrations.RemoveField(
            model_name='experimentconfig',
            name='arx_nk',
        ),
        migrations.RemoveField(
            model_name='experimentconfig',
            name='test_ratio',
        ),
        migrations.RemoveField(
            model_name='experimentconfig',
            name='train_ratio',
        ),
        migrations.RemoveField(
            model_name='experimentconfig',
            name='val_ratio',
        ),
        migrations.AlterField(
            model_name='evaluationsummary',
            name='slice_type',
            field=models.CharField(choices=[('online', 'Online')], max_length=15),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='run_type',
            field=models.CharField(choices=[('live', 'Live')], default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinecycle',
            name='ingest_dedupe_key',
            field=models.CharField(help_text='Stable key for DB uniqueness: live=run+UTC timestamp.', max_length=191),
        ),
        migrations.AlterField(
            model_name='pipelinecycle',
            name='slice_type',
            field=models.CharField(choices=[('online', 'Online')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pipelinecycle',
            name='source_type',
            field=models.CharField(choices=[('live', 'Live Sensor')], default='live', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('slice_type__in', ['online'])), name='chk_cycles_slice_type'),
        ),
        migrations.AddConstraint(
            model_name='pipelinecycle',
            constraint=models.CheckConstraint(check=models.Q(('source_type__in', ['live'])), name='chk_cycles_source_type'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_arx_artifacts_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='ARXArtifact',
                ),
            ],
        ),
    ]
