# Generated by Codex on 2026-05-08

from datetime import timezone

from django.db import migrations, models
from django.db.models import Count, Max

_RAW_SENSOR_FIELDS = (
    "raw_soil_moisture",
    "raw_temperature",
    "raw_humidity",
    "raw_light",
    "raw_drip",
    "raw_mist",
    "raw_fan",
)


def _raw_sensor_tuple(cycle):
    return tuple(getattr(cycle, field) for field in _RAW_SENSOR_FIELDS)


def _live_ingest_key(run_id, sample_ts):
    ts = sample_ts
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    else:
        ts = ts.astimezone(timezone.utc)
    return f"live|{run_id}|{ts.isoformat()}"


def _delete_duplicate_live_timestamps(PipelineCycle):
    """Delete only duplicate timestamp rows that are safe to trim.

    A non-tail duplicate changes the Kalman history if deleted after the fact,
    because later posterior rows were computed with that extra step present.
    Payload conflicts also require manual correction. This matches the safety
    model used by migration 0005.
    """
    duplicate_groups = (
        PipelineCycle.objects.values("run_id", "sample_ts")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for group in duplicate_groups.iterator():
        rows = list(
            PipelineCycle.objects.filter(
                run_id=group["run_id"],
                sample_ts=group["sample_ts"],
            ).order_by("cycle_index", "id")
        )
        if len(rows) < 2:
            continue
        ids = [row.id for row in rows]
        max_idx_in_group = max(row.cycle_index for row in rows)
        run_max_idx = (
            PipelineCycle.objects.filter(run_id=group["run_id"])
            .aggregate(m=Max("cycle_index"))
            .get("m")
        )
        if run_max_idx is None:
            run_max_idx = max_idx_in_group

        ref_payload = _raw_sensor_tuple(rows[0])
        same_payload = all(_raw_sensor_tuple(row) == ref_payload for row in rows[1:])
        if not same_payload:
            raise ValueError(
                "estimation migration 0007: duplicate live (run_id, sample_ts) "
                "with conflicting raw sensor payloads. "
                f"run_id={group['run_id']}, sample_ts={group['sample_ts']!r}, "
                f"pipeline_cycles.id in {ids}. "
                "Resolve manually, then run migrate again."
            )

        if run_max_idx > max_idx_in_group:
            raise ValueError(
                "estimation migration 0007: duplicate live (run_id, sample_ts) "
                "has identical raw payloads, but later cycles exist whose Kalman "
                "state may depend on the duplicate row. "
                f"run_id={group['run_id']}, sample_ts={group['sample_ts']!r}, "
                f"max duplicate cycle_index={max_idx_in_group}, "
                f"run max cycle_index={run_max_idx}, pipeline_cycles.id in {ids}. "
                "Replay/recompute the run from a clean snapshot, or trim later "
                "cycles manually, then run migrate again."
            )

        delete_ids = [row.id for row in rows[1:]]
        if delete_ids:
            PipelineCycle.objects.filter(id__in=delete_ids).delete()


def _backfill_live_ingest_keys(PipelineCycle, batch_size=500):
    rows = []
    for cycle in PipelineCycle.objects.only("id", "ingest_dedupe_key").iterator():
        temp_key = f"tmp-live-cleanup|{cycle.id}"
        if cycle.ingest_dedupe_key != temp_key:
            cycle.ingest_dedupe_key = temp_key
            rows.append(cycle)
        if len(rows) >= batch_size:
            PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])
            rows = []
    if rows:
        PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])

    rows = []
    for cycle in PipelineCycle.objects.only(
        "id",
        "run_id",
        "sample_ts",
        "ingest_dedupe_key",
    ).iterator():
        key = _live_ingest_key(cycle.run_id, cycle.sample_ts)
        if cycle.ingest_dedupe_key != key:
            cycle.ingest_dedupe_key = key
            rows.append(cycle)
        if len(rows) >= batch_size:
            PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])
            rows = []
    if rows:
        PipelineCycle.objects.bulk_update(rows, ["ingest_dedupe_key"])


def backfill_live_dedupe_keys(apps, schema_editor):
    PipelineCycle = apps.get_model("estimation", "PipelineCycle")
    _delete_duplicate_live_timestamps(PipelineCycle)
    _backfill_live_ingest_keys(PipelineCycle)
    PipelineCycle.objects.exclude(
        preprocess_status__in=["valid", "skipped"]
    ).update(preprocess_status="skipped")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("estimation", "0006_live_only_cleanup"),
    ]

    operations = [
        migrations.RunPython(backfill_live_dedupe_keys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="experimentconfig",
            name="preprocessing_policy",
        ),
        migrations.AlterField(
            model_name="pipelinecycle",
            name="preprocess_status",
            field=models.CharField(
                choices=[("valid", "Valid"), ("skipped", "Skipped")],
                default="valid",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="pipelinecycle",
            name="chk_cycles_preprocess_status",
        ),
        migrations.AddConstraint(
            model_name="pipelinecycle",
            constraint=models.CheckConstraint(
                check=models.Q(preprocess_status__in=["valid", "skipped"]),
                name="chk_cycles_preprocess_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="experimentrun",
            constraint=models.CheckConstraint(
                check=models.Q(run_type="live"),
                name="chk_runs_run_type_live",
            ),
        ),
    ]
