# Generated by Codex on 2026-05-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_GREENHOUSE_NAME = "Default Greenhouse"
LEGACY_USERNAME = "legacy_greenhouse_owner"


def backfill_greenhouse_scope(apps, schema_editor):
    ExperimentRun = apps.get_model("estimation", "ExperimentRun")
    PipelineCycle = apps.get_model("estimation", "PipelineCycle")
    Greenhouse = apps.get_model("estimation", "Greenhouse")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    legacy_user = None

    def _legacy_user_id():
        nonlocal legacy_user
        if legacy_user is None:
            legacy_user, _ = User.objects.get_or_create(
                username=LEGACY_USERNAME,
                defaults={
                    "password": "!",
                    "is_active": False,
                },
            )
        return legacy_user.pk

    greenhouse_by_owner: dict[int, int] = {}

    def _greenhouse_id_for_owner(owner_id: int) -> int:
        if owner_id not in greenhouse_by_owner:
            greenhouse, _ = Greenhouse.objects.get_or_create(
                owner_id=owner_id,
                name=DEFAULT_GREENHOUSE_NAME,
                defaults={"is_active": True},
            )
            greenhouse_by_owner[owner_id] = greenhouse.pk
        return greenhouse_by_owner[owner_id]

    runs_to_update = []
    for run in ExperimentRun.objects.only("id", "owner_id", "greenhouse_id").iterator():
        owner_id = run.owner_id or _legacy_user_id()
        run.greenhouse_id = _greenhouse_id_for_owner(owner_id)
        runs_to_update.append(run)
        if len(runs_to_update) >= 1000:
            ExperimentRun.objects.bulk_update(runs_to_update, ["greenhouse"])
            runs_to_update.clear()
    if runs_to_update:
        ExperimentRun.objects.bulk_update(runs_to_update, ["greenhouse"])

    for run in ExperimentRun.objects.exclude(greenhouse_id__isnull=True).only(
        "id",
        "greenhouse_id",
    ).iterator():
        PipelineCycle.objects.filter(
            run_id=run.pk,
            greenhouse_id__isnull=True,
        ).update(greenhouse_id=run.greenhouse_id)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estimation", "0008_live_status_and_text_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Greenhouse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User that owns this greenhouse and its live runs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="greenhouses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "greenhouses",
            },
        ),
        migrations.AddField(
            model_name="experimentrun",
            name="greenhouse",
            field=models.ForeignKey(
                help_text="Greenhouse this live run belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="estimation.greenhouse",
            ),
        ),
        migrations.AddField(
            model_name="pipelinecycle",
            name="greenhouse",
            field=models.ForeignKey(
                help_text="Denormalized greenhouse scope for latest-state queries",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cycles",
                to="estimation.greenhouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="greenhouse",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"),
                name="uq_greenhouses_owner_name",
            ),
        ),
        migrations.AddIndex(
            model_name="greenhouse",
            index=models.Index(
                fields=["owner", "is_active"],
                name="idx_greenhouses_owner_active",
            ),
        ),
        migrations.AddIndex(
            model_name="greenhouse",
            index=models.Index(fields=["created_at"], name="idx_greenhouses_created"),
        ),
        migrations.RunPython(backfill_greenhouse_scope, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="experimentrun",
            name="greenhouse",
            field=models.ForeignKey(
                help_text="Greenhouse this live run belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="estimation.greenhouse",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinecycle",
            name="greenhouse",
            field=models.ForeignKey(
                help_text="Denormalized greenhouse scope for latest-state queries",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cycles",
                to="estimation.greenhouse",
            ),
        ),
        migrations.RemoveIndex(
            model_name="experimentrun",
            name="idx_runs_owner",
        ),
        migrations.RemoveField(
            model_name="experimentrun",
            name="owner",
        ),
        migrations.AddIndex(
            model_name="experimentrun",
            index=models.Index(
                fields=["greenhouse", "created_at"],
                name="idx_runs_greenhouse_created",
            ),
        ),
        migrations.AddIndex(
            model_name="experimentrun",
            index=models.Index(
                fields=["greenhouse", "status"],
                name="idx_runs_greenhouse_status",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinecycle",
            index=models.Index(
                fields=["greenhouse", "sample_ts"],
                name="idx_cycles_greenhouse_ts",
            ),
        ),
    ]
