# Generated by Django 4.2.30 on 2026-05-09 07:05

from django.db import migrations, models
import django.db.models.deletion


# Rollback note: this migration is additive. Reversing it drops the AMPC
# profile/recommendation tables and therefore loses AMPC audit history created
# after deployment; no existing Kalman/ingest rows are modified.
class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0009_greenhouse_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseControlProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='generic', max_length=100)),
                ('crop_kc', models.FloatField(default=1.0)),
                ('target_low', models.FloatField(default=55.0)),
                ('target_high', models.FloatField(default=65.0)),
                ('pump_max_seconds', models.FloatField(default=300.0)),
                ('soft_daily_pump_cap_seconds', models.FloatField(default=1800.0)),
                ('actuator_enabled', models.BooleanField(default=False)),
                ('step_seconds', models.IntegerField(default=300)),
                ('horizon_steps', models.IntegerField(default=12)),
                ('pump_min_seconds', models.FloatField(default=0.0)),
                ('pump_grid_seconds', models.FloatField(default=30.0)),
                ('cost_band_violation', models.FloatField(default=10.0)),
                ('cost_water_use', models.FloatField(default=0.2)),
                ('cost_switching', models.FloatField(default=0.5)),
                ('cost_daily_cap_excess', models.FloatField(default=2.0)),
                ('cost_terminal_band_violation', models.FloatField(default=20.0)),
                ('adaptive_enabled', models.BooleanField(default=True)),
                ('adaptive_bias_window', models.IntegerField(default=12)),
                ('adaptive_max_abs_bias', models.FloatField(default=5.0)),
                ('safety_stale_after_seconds', models.IntegerField(default=600)),
                ('actuator_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('actuator_bearer_token_env', models.CharField(blank=True, max_length=128, null=True)),
                ('actuator_timeout_seconds', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.OneToOneField(help_text='Greenhouse controlled by this AMPC profile', on_delete=django.db.models.deletion.CASCADE, related_name='control_profile', to='estimation.greenhouse')),
            ],
            options={
                'db_table': 'greenhouse_control_profiles',
            },
        ),
        migrations.CreateModel(
            name='AMPCRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ampc', 'AMPC')], default='ampc', max_length=20)),
                ('pump_seconds', models.FloatField(default=0.0)),
                ('step_seconds', models.IntegerField(default=300)),
                ('predicted_soil_moisture_json', models.JSONField(default=list)),
                ('target_low', models.FloatField(default=55.0)),
                ('target_high', models.FloatField(default=65.0)),
                ('cost', models.FloatField(default=0.0)),
                ('safety_status', models.CharField(choices=[('safe', 'Safe'), ('pump_off_failsafe', 'Pump Off Failsafe'), ('config_error', 'Config Error'), ('stale_sample', 'Stale Sample'), ('model_error', 'Model Error'), ('solver_error', 'Solver Error'), ('actuator_error', 'Actuator Error')], default='pump_off_failsafe', max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('bias_correction', models.FloatField(default=0.0)),
                ('bias_window_count', models.IntegerField(default=0)),
                ('used_today_pump_seconds', models.FloatField(default=0.0)),
                ('config_snapshot_json', models.JSONField(default=dict)),
                ('state_snapshot_json', models.JSONField(default=dict)),
                ('actuator_enabled', models.BooleanField(default=False)),
                ('actuator_executed', models.BooleanField(default=False)),
                ('actuator_status', models.CharField(default='disabled', max_length=40)),
                ('actuator_command_json', models.JSONField(blank=True, null=True)),
                ('actuator_http_status_code', models.IntegerField(blank=True, null=True)),
                ('actuator_alert', models.CharField(blank=True, max_length=255, null=True)),
                ('actuator_error', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ampc_recommendations', to='estimation.greenhouse')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampc_recommendations', to='estimation.experimentrun')),
                ('state_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampc_recommendations', to='estimation.pipelinecycle')),
            ],
            options={
                'db_table': 'ampc_recommendations',
            },
        ),
        migrations.AddConstraint(
            model_name='greenhousecontrolprofile',
            constraint=models.CheckConstraint(check=models.Q(('target_low__lt', models.F('target_high'))), name='chk_profile_target_band'),
        ),
        migrations.AddConstraint(
            model_name='greenhousecontrolprofile',
            constraint=models.CheckConstraint(check=models.Q(('pump_min_seconds__gte', 0.0), ('pump_max_seconds__gt', models.F('pump_min_seconds')), ('pump_grid_seconds__gt', 0.0), ('pump_grid_seconds__lte', models.F('pump_max_seconds'))), name='chk_profile_pump_bounds'),
        ),
        migrations.AddConstraint(
            model_name='greenhousecontrolprofile',
            constraint=models.CheckConstraint(check=models.Q(('step_seconds__gt', 0), ('horizon_steps__gt', 0), ('safety_stale_after_seconds__gt', 0), ('adaptive_bias_window__gt', 0)), name='chk_profile_positive_steps'),
        ),
        migrations.AddConstraint(
            model_name='greenhousecontrolprofile',
            constraint=models.CheckConstraint(check=models.Q(('crop_kc__gt', 0.0), ('soft_daily_pump_cap_seconds__gt', 0.0), ('adaptive_max_abs_bias__gte', 0.0), ('actuator_timeout_seconds__gt', 0.0)), name='chk_profile_positive_values'),
        ),
        migrations.AddConstraint(
            model_name='greenhousecontrolprofile',
            constraint=models.CheckConstraint(check=models.Q(('cost_band_violation__gte', 0.0), ('cost_water_use__gte', 0.0), ('cost_switching__gte', 0.0), ('cost_daily_cap_excess__gte', 0.0), ('cost_terminal_band_violation__gte', 0.0)), name='chk_profile_cost_nonneg'),
        ),
        migrations.AddIndex(
            model_name='ampcrecommendation',
            index=models.Index(fields=['greenhouse', 'created_at'], name='idx_ampc_greenhouse_created'),
        ),
        migrations.AddIndex(
            model_name='ampcrecommendation',
            index=models.Index(fields=['greenhouse', 'safety_status'], name='idx_ampc_greenhouse_status'),
        ),
        migrations.AddConstraint(
            model_name='ampcrecommendation',
            constraint=models.CheckConstraint(check=models.Q(('pump_seconds__gte', 0.0)), name='chk_ampc_pump_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='ampcrecommendation',
            constraint=models.CheckConstraint(check=models.Q(('step_seconds__gt', 0)), name='chk_ampc_step_positive'),
        ),
        migrations.AddConstraint(
            model_name='ampcrecommendation',
            constraint=models.CheckConstraint(check=models.Q(('cost__gte', 0.0)), name='chk_ampc_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='ampcrecommendation',
            constraint=models.CheckConstraint(check=models.Q(('target_low__lt', models.F('target_high'))), name='chk_ampc_target_band'),
        ),
        migrations.AddConstraint(
            model_name='ampcrecommendation',
            constraint=models.CheckConstraint(check=models.Q(('bias_window_count__gte', 0)), name='chk_ampc_bias_count_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='ampcrecommendation',
            constraint=models.CheckConstraint(check=models.Q(('used_today_pump_seconds__gte', 0.0)), name='chk_ampc_used_today_nonneg'),
        ),
    ]
